/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

/**
 *
 * @author mhass
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainhead = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        serverip = new javax.swing.JLabel();
        port = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        userpass = new javax.swing.JTextField();
        fixfield1 = new javax.swing.JTextField();
        fixfield2 = new javax.swing.JTextField();
        CloseB = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Mainhead.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        Mainhead.setForeground(new java.awt.Color(255, 255, 255));
        Mainhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mainhead.setText("LOGIN");
        Mainhead.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                MainheadAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        getContentPane().add(Mainhead);
        Mainhead.setBounds(180, 50, 160, 58);

        User.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("USERNAME");
        getContentPane().add(User);
        User.setBounds(80, 140, 90, 21);

        Password.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("PASSWORD");
        getContentPane().add(Password);
        Password.setBounds(80, 170, 90, 21);

        serverip.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        serverip.setForeground(new java.awt.Color(255, 255, 255));
        serverip.setText("SERVER IP:");
        getContentPane().add(serverip);
        serverip.setBounds(40, 240, 80, 21);

        port.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        port.setForeground(new java.awt.Color(255, 255, 255));
        port.setText("PORT      :");
        getContentPane().add(port);
        port.setBounds(40, 270, 80, 21);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(180, 140, 174, 20);

        userpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpassActionPerformed(evt);
            }
        });
        getContentPane().add(userpass);
        userpass.setBounds(180, 170, 174, 20);

        fixfield1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fixfield1);
        fixfield1.setBounds(140, 240, 174, 20);

        fixfield2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fixfield2);
        fixfield2.setBounds(140, 270, 174, 20);

        CloseB.setBackground(new java.awt.Color(255, 0, 51));
        CloseB.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        CloseB.setForeground(new java.awt.Color(255, 255, 255));
        CloseB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseB.setText("CLOSE");
        CloseB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CloseB.setOpaque(true);
        getContentPane().add(CloseB);
        CloseB.setBounds(450, 290, 60, 17);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loginbg.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, -2, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpassActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void MainheadAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_MainheadAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_MainheadAncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel Mainhead;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel User;
    private javax.swing.JTextField fixfield1;
    private javax.swing.JTextField fixfield2;
    private javax.swing.JLabel port;
    private javax.swing.JLabel serverip;
    private javax.swing.JTextField username;
    private javax.swing.JTextField userpass;
    // End of variables declaration//GEN-END:variables
}
